# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 60af2155981f1a90f98052b8f0e5500dfb7219fa3af73cdcd83d1195332bf1824c66f97747b1701ee0d2711e49617794af6ab74714d09a0bc36632cadb53568d

test:
  secret_key_base: d50ca1b88bd17fac55293f4c10c12df7d3c098a5ad1534551fed3dd3de1312c13010a49d7e9880f7066209834563c855205fe0c59fd3e4704f557b86d4cfcf7f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
